22-D11: add template and input files

diff --git a/2022/rust/Makefile b/2022/rust/Makefile
--- a/2022/rust/Makefile
+++ b/2022/rust/Makefile
@@ -14,6 +14,9 @@ p2-watch:
 	$(call watch_problem,2)
 
 get-input:
+	[[ -n "$(d)" ]] || { echo "specify 'd=...' for the day"; return 1 }
 	[[ $$AOC_COOKIE ]] || { echo 'set $$AOC_COOKIE'; return 1 }
-	curl -sL --cookie "session=$$AOC_COOKIE" __aoc_url__ > input && \
-		echo 'input saved?' || echo 'failed!'
+	local padded_day=$$( python -c "print('$(d)'.zfill(2), end=None)" ) && \
+		curl -sL --cookie "session=$$AOC_COOKIE" \
+			https://adventofcode.com/2022/day/$(d)/input > input/day$${padded_day} && \
+			echo 'input saved?' || echo 'failed!'
